spring:
  datasource:
    url: jdbc:mysql://yapp.cmarogp1dz0t.ap-northeast-2.rds.amazonaws.com/zone?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 10000
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate:
        #show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

spring.datasource.password: findmyzone!

---

spring.profiles: logging-info
logging:
  file.path: logs/application.log
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.quartz.core: INFO
    com.mysql.cj.jdbc.Driver: INFO

---
spring.profiles: logging-debug
logging:
  file.path: logs/application.log
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.quartz.core: DEBUG
    com.mysql.cj.jdbc.Driver: DEBUG

---
spring.profiles: logging-daily
logging:
  config: classpath:log/logback-spring.xml

---
spring.profiles: logging-warn
logging:
  config: classpath:log/logback-spring-warn.xml