spring:
  datasource:
    url: jdbc:mysql://localhost:3306/last_word?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace